Created a series of linters to perform various validations
dassana-io/dassana pull request #135
Opened 2021-08-24 20:15 UTC by ak-dassana

2021-08-25 01:44 UTC, ak-dassana commented
@parth-dassana G just reminded me of this but the file config-recording-not-enabled.yaml is not valid according to the resource-hierarchy.yaml mapping. Not sure which file to update so need your input

2021-09-01 22:23 UTC, parth-dassana requested changes
Couple things

2021-09-01 22:23 UTC, parth-dassana commented on engine/src/main/java/app/dassana/core/api/linter/VendorLinter.java
> +		"iam-role-not-enabled-for-ec2.yaml", "vpc-route-table-is-overly-permissive.yaml"};
This cannot be here for sure. Please delete the files or something of that sort in the future.

2021-09-01 22:23 UTC, parth-dassana commented on engine/src/main/java/app/dassana/core/api/linter/VendorLinter.java
> +						"resourceContainer", "region", "service", "resourceType", "resourceId"};
Pretty sure this is handled by `engine/src/main/java/app/dassana/core/workflow/processor/RequestProcessor.java`

2021-09-07 19:09 UTC, closed without merging