Prisma Normalizer
dassana-io/dassana pull request #173
Opened 2021-09-03 18:19 UTC by gauravphoenix

2021-09-03 18:44 UTC, parth-dassana requested changes
Nice work, just a couple of comments

2021-09-03 18:44 UTC, parth-dassana commented on content/actions/normalizer-lookup/README.md
> +# Normalizer Lookforward
```suggestion
# Normalizer Resource Hierarchy Lookup
```

2021-09-03 18:44 UTC, parth-dassana commented on content/actions/normalizer-lookup/README.md
> +looks forward in the policy context workflows to properly allocate the aforementioned fields.
```suggestion
If the normalizer cannot normalize the `csp`, `service`, and `resourceType` fields from an alert, this action uses the alert's `vendorPolicyId` to find the relevant policy context workflow (if applicable) to fill out the empty fields.
```

2021-09-03 18:44 UTC, parth-dassana commented on content/actions/prisma-cloud-normalizer/README.md
> +This action extracts and normalizes alerts from Prisma Cloud into Dassana-esque format.
```suggestion
This action extracts and normalizes alerts from Prisma Cloud into Dassana-esque format. Currently, only config type alerts for AWS are normalized.
```

2021-09-03 18:44 UTC, parth-dassana commented on content/actions/prisma-cloud-normalizer/src/handler.py
> +        canonicalId=event.resource.data.arn,
This may not always be present. If it isn't present, then this won't fail yes? If so you should handle it.

2021-09-03 18:44 UTC, parth-dassana commented on content/actions/what-is-exposure-of-ec2-instance/README.md
> +   "region": "us-east-1"
nit: indentation is off

2021-09-03 18:44 UTC, parth-dassana commented on content/workflows/vendors/prisma-cloud/prisma-cloud.yaml
> +  - id: lookup
👍🏽

2021-09-06 17:19 UTC, dassana-junix commented on content/actions/prisma-cloud-normalizer/src/handler.py
> +        canonicalId=event.resource.data.arn,
The Pydantic data model will render it as null if it doesn't exist in the source -- if it isn't present, it won't fail.

2021-09-06 17:22 UTC, dassana-junix commented
Closes #

2021-09-06 17:23 UTC, dassana-junix commented
Closes #163, #162, #125

2021-09-06 17:30 UTC, parth-dassana approved these changes

2021-09-06 17:33 UTC, merged