Cis 1.2 iam changes
dassana-io/dassana pull request #38
Opened 2021-08-05 18:07 UTC by ak-dassana

Added a series of changes to the policies of the vendors PrismaCloud and SecurityHub

2021-08-05 23:07 UTC, parth-dassana requested changes
Looks great! Just a few comments.

2021-08-05 23:07 UTC, parth-dassana commented on content/workflows/policies/csp/aws/service/iam/resources/policy/iam-support-policy-exists.yaml
> +name: "IAM Support Policy Exists"
```suggestion
id: "iam-support-role-exists"
name: "IAM Support Role Exists"
```

2021-08-05 23:07 UTC, parth-dassana commented on content/workflows/policies/csp/aws/service/iam/resources/user/iam-user-policy-exists.yaml
> +subcategory: authentication
@dassana-junix / @ak-dassana - I feel this is more of an `authorization` issue. Do you guys disagree?

2021-08-05 23:20 UTC, dassana-junix commented on content/workflows/policies/csp/aws/service/ec2/resources/instance/iam-role-not-enabled.yaml
> +subcategory: firewall
IAM.Authorization seems to be the more valid categorization here.

2021-08-05 23:20 UTC, dassana-junix commented on content/workflows/policies/csp/aws/service/iam/resources/user/iam-user-policy-exists.yaml
> +subcategory: authentication
It's authorization necause IAM user policy is about what permissions user has, authentication would be more of an access key related policy.

2021-08-06 00:09 UTC, parth-dassana requested changes
Couple more!

2021-08-06 00:09 UTC, parth-dassana commented on content/workflows/policies/csp/aws/service/iam/resources/policy/iam-no-admin-access.yaml
> +schema: 1.0
Please rename this file to match the id of the policy

2021-08-06 00:09 UTC, parth-dassana commented on content/workflows/policies/csp/aws/service/iam/resources/policy/iam-role-not-enabled.yaml
> +id: "iam-role-not-enabled"
```suggestion
id: "iam-role-not-enabled-for-ec2"
```

Please also rename the file

2021-08-06 00:09 UTC, parth-dassana commented on content/workflows/policies/csp/aws/service/iam/resources/policy/iam-support-policy-exists.yaml
> +schema: 1.0
Please rename file to match the id

2021-08-06 00:26 UTC, parth-dassana approved these changes
LGTM! Nice work!

2021-08-06 00:35 UTC, merged