Cis v1.2 logging network
dassana-io/dassana pull request #77
Opened 2021-08-10 21:11 UTC by ak-dassana

2021-08-11 22:06 UTC, parth-dassana commented on content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloud-trail-encryption-enabled.yaml
> +id: "cloud-trail-encryption-enabled"
Policy name, id, and file name should be the actual issue not the recommended setting.

2021-08-11 23:06 UTC, dassana-junix requested changes

2021-08-11 23:06 UTC, dassana-junix commented on content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/logs-validation-not-enabled.yaml
> +id: logs-validation-not-enabled
`logs-validation-not-enabled-in-all-regions` is a better name to encapsulate both policies

2021-08-11 23:54 UTC, parth-dassana requested changes
A couple more

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloud-trail-encryption-not-enabled.yaml
> +schema: 1.0
Please rename file and id to be `cloudtrail-encryption-not-enabled`. Cloudtrail is a full word not needing a hypen in the middle.

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloud-trail-encryption-not-enabled.yaml
> +name: Cloud trail encryption not enabled
```suggestion
name: CloudTrail encryption not enabled
```

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloud-watch-logs-not-enabled.yaml
> +id: cloud-watch-logs-not-enabled
```suggestion
id: cloudwatch-logs-not-enabled
```

Please also rename file to not have a hypen between cloud and watch

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/cloudtrail/resources/trail/policy-context/cloud-watch-logs-not-enabled.yaml
> +name: Cloud watch logs not enabled
```suggestion
name: CloudWatch logs not enabled
```

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/ec2/resources/route-table/policy-context/vpc-route-table-not-traffic-restricted.yaml
> +id: vpc-route-table-not-traffic-restricted
```suggestion
id: vpc-route-table-is-overly-permissive
```

Please rename file as well

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/ec2/resources/route-table/policy-context/vpc-route-table-not-traffic-restricted.yaml
> +name: VPC route table not traffic restricted
```suggestion
name: VPC route table is overly permissive
```

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/common-ports-are-open.yaml
> +schema: 1.0
We actually don't need this file. This should all be added to the existing `sg-is-wide-open` policy.

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/ec2/resources/security-group/policy-context/default-security-group-is-open.yaml
> +schema: 1.0
We don't need this file, please add everything to the `sg-is-wide-open` policy

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/kms/resources/cmk/policy-context/backing-key-rotation-not-enabled.yaml
> +id: backing-key-rotation-not-enabled
```suggestion
id: cmk-rotation-not-enabled
```

Please rename file as well

2021-08-11 23:54 UTC, parth-dassana commented on content/workflows/csp/aws/service/kms/resources/cmk/policy-context/backing-key-rotation-not-enabled.yaml
> +name: Backing key rotation not enabled
```suggestion
name: CMK rotation not enabled
```

2021-08-12 01:34 UTC, parth-dassana approved these changes
LGTM, fantastic work!

2021-08-12 01:44 UTC, parth-dassana approved these changes
LGTM

2021-08-12 01:45 UTC, merged